In [5]:
i=0
while(i<11):
    print(i,end=" ")
    i+=1

0 1 2 3 4 5 6 7 8 9 10 

In [3]:
def fac(n):
    if(n==0):
        return 1
    return n*fac(n-1)
print(fac(20))

2432902008176640000


In [19]:
str="welcome"
a=0

In [21]:
def s(str,a):
    count=0
    while(count<10):
        print(str)
        count=count+1
        print("Thank you")

In [8]:
s(str)

welcome
thank you
welcome
thank you
welcome
thank you
welcome
thank you
welcome
thank you
welcome
thank you
welcome
thank you
welcome
thank you
welcome
thank you
welcome
thank you


In [23]:
def s(str,a):
    count=0
    while(count<10):
        print(str)
        count=count+1
        print(a)

In [28]:
s(str,a)

welcome
0
welcome
0
welcome
0
welcome
0
welcome
0
welcome
0
welcome
0
welcome
0
welcome
0
welcome
0


In [29]:
def s(str,a):
    while(a<10):
        print(str)
        a+=1
        print(a)

In [30]:
s(str,a)

welcome
1
welcome
2
welcome
3
welcome
4
welcome
5
welcome
6
welcome
7
welcome
8
welcome
9
welcome
10


In [25]:
l=[10,"welcome",0]

In [26]:
l

[10, 'welcome', 0]

In [27]:
s(l,a)

[10, 'welcome', 0]
0
[10, 'welcome', 0]
0
[10, 'welcome', 0]
0
[10, 'welcome', 0]
0
[10, 'welcome', 0]
0
[10, 'welcome', 0]
0
[10, 'welcome', 0]
0
[10, 'welcome', 0]
0
[10, 'welcome', 0]
0
[10, 'welcome', 0]
0


In [31]:
s(l,a)

[10, 'welcome', 0]
1
[10, 'welcome', 0]
2
[10, 'welcome', 0]
3
[10, 'welcome', 0]
4
[10, 'welcome', 0]
5
[10, 'welcome', 0]
6
[10, 'welcome', 0]
7
[10, 'welcome', 0]
8
[10, 'welcome', 0]
9
[10, 'welcome', 0]
10


In [32]:
s(l[1],a)

welcome
1
welcome
2
welcome
3
welcome
4
welcome
5
welcome
6
welcome
7
welcome
8
welcome
9
welcome
10


In [33]:
import numpy as np

In [35]:
a=np.array([1,2,3,4,5])

In [36]:
a

array([1, 2, 3, 4, 5])

In [37]:
a=np.array([[1,2],[3,4]])

In [38]:
a

array([[1, 2],
       [3, 4]])

In [40]:
a=np.array([1,2,3,4,5,6])

In [41]:
a

array([1, 2, 3, 4, 5, 6])

In [42]:
a=np.array([1,2,3,4,5],ndmin=2)

In [43]:
a

array([[1, 2, 3, 4, 5]])

In [44]:
a.shape

(1, 5)

In [45]:
a=np.array([[1,2,3],[4,5,6]])

In [46]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
a

(3, 2)

In [65]:
a=np.arange(40,60)

In [66]:
a

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
       57, 58, 59])

In [67]:
a.shape= 4,5

In [68]:
a

array([[40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [69]:
x=np.zeros(3)

In [70]:
x

array([0., 0., 0.])

In [ ]:
x.np.